# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# One affine piece of the piecewise-linear value function. Element type of
# `StageCuts.cuts`.
#
# `coefficients` length equals the enclosing `StageCuts.state_dimension`. The
# piece bounds the value function as `intercept + coefficients · x`.
class AffinePiece(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AffinePiece()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAffinePiece(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AffinePieceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # AffinePiece
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Unique identifier for this piece across all iterations.
    # AffinePiece
    def PieceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # LP row position. Required for artifact reproducibility and
    # basis warm-starting.
    # AffinePiece
    def SlotIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Training iteration that generated this piece.
    # AffinePiece
    def Iteration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Forward-pass index within the generating iteration.
    # AffinePiece
    def ForwardPassIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Pre-computed affine intercept: `alpha - beta' * x_hat`, where
    # `x_hat` is the state at the generating forward-pass node. Slot id 4
    # was the pre-v0.5.0 `domination_count`; reclaimed under the 0.14
    # format break, which cleanly rejects any earlier artifact.
    # AffinePiece
    def Intercept(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Gradient coefficient vector. Length equals
    # `StageCuts.state_dimension`.
    # AffinePiece
    def Coefficients(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # AffinePiece
    def CoefficientsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # AffinePiece
    def CoefficientsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AffinePiece
    def CoefficientsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Whether this piece is currently active in the LP. Inactive pieces
    # are retained for potential reactivation.
    # AffinePiece
    def IsActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def AffinePieceStart(builder):
    builder.StartObject(8)

def Start(builder):
    AffinePieceStart(builder)

def AffinePieceAddPieceId(builder, pieceId):
    builder.PrependUint64Slot(0, pieceId, 0)

def AddPieceId(builder, pieceId):
    AffinePieceAddPieceId(builder, pieceId)

def AffinePieceAddSlotIndex(builder, slotIndex):
    builder.PrependUint32Slot(1, slotIndex, 0)

def AddSlotIndex(builder, slotIndex):
    AffinePieceAddSlotIndex(builder, slotIndex)

def AffinePieceAddIteration(builder, iteration):
    builder.PrependUint32Slot(2, iteration, 0)

def AddIteration(builder, iteration):
    AffinePieceAddIteration(builder, iteration)

def AffinePieceAddForwardPassIndex(builder, forwardPassIndex):
    builder.PrependUint32Slot(3, forwardPassIndex, 0)

def AddForwardPassIndex(builder, forwardPassIndex):
    AffinePieceAddForwardPassIndex(builder, forwardPassIndex)

def AffinePieceAddIntercept(builder, intercept):
    builder.PrependFloat64Slot(4, intercept, 0.0)

def AddIntercept(builder, intercept):
    AffinePieceAddIntercept(builder, intercept)

def AffinePieceAddCoefficients(builder, coefficients):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(coefficients), 0)

def AddCoefficients(builder, coefficients):
    AffinePieceAddCoefficients(builder, coefficients)

def AffinePieceStartCoefficientsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartCoefficientsVector(builder, numElems: int) -> int:
    return AffinePieceStartCoefficientsVector(builder, numElems)

def AffinePieceAddIsActive(builder, isActive):
    builder.PrependBoolSlot(6, isActive, 0)

def AddIsActive(builder, isActive):
    AffinePieceAddIsActive(builder, isActive)

def AffinePieceEnd(builder):
    return builder.EndObject()

def End(builder):
    return AffinePieceEnd(builder)
