# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Root table for the study-global checkpoint manifest: the artifact format
# version, the stage count, the policy-graph manifest (nodes, edges, pool-set
# size), and the producer provenance block.
#
# Field ids start fresh at 0 and reuse none of the burned slots noted in the
# header (those are per-table: `AffinePiece` id 7, `EntitySlot` id 4). The
# three `float64` provenance fields (`final_lower_bound`, `best_upper_bound`,
# `cost_scale_factor`) carry no explicit default, so an absent field decodes as
# "no value recorded" rather than a spurious `0.0`.
class CheckpointManifest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CheckpointManifest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckpointManifest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CheckpointManifestBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # CheckpointManifest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # On-disk artifact format version; a reader rejects any other value.
    # CheckpointManifest
    def FormatVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Producer crate version that wrote this checkpoint.
    # CheckpointManifest
    def CobreVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ISO 8601 timestamp when the checkpoint was written.
    # CheckpointManifest
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Number of stages the graph manifest spans.
    # CheckpointManifest
    def NumStages(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Number of distinct pools (the pool-set size).
    # CheckpointManifest
    def NPools(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Graph-manifest nodes, in canonical order.
    # CheckpointManifest
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cobre.IO.Policy.ManifestNode import ManifestNode
            obj = ManifestNode()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckpointManifest
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CheckpointManifest
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Graph-manifest directed edges with their transition probabilities.
    # CheckpointManifest
    def Edges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cobre.IO.Policy.ManifestEdge import ManifestEdge
            obj = ManifestEdge()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CheckpointManifest
    def EdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CheckpointManifest
    def EdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Producer training iterations completed at write time.
    # CheckpointManifest
    def CompletedIterations(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Lower bound after the final completed iteration.
    # CheckpointManifest
    def FinalLowerBound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Last iteration's upper bound; absent when the producer recorded none.
    # CheckpointManifest
    def BestUpperBound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Maximum iterations configured for the run.
    # CheckpointManifest
    def MaxIterations(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Forward passes per iteration.
    # CheckpointManifest
    def ForwardPasses(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Pieces loaded from a previous artifact at run start.
    # CheckpointManifest
    def WarmStartCuts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Per-pool warm-start piece counts, in pool-id order.
    # CheckpointManifest
    def WarmStartCounts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CheckpointManifest
    def WarmStartCountsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # CheckpointManifest
    def WarmStartCountsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CheckpointManifest
    def WarmStartCountsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # RNG seed used by the scenario sampler.
    # CheckpointManifest
    def RngSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Total visited states across all nodes.
    # CheckpointManifest
    def TotalVisitedStates(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Block mode the checkpoint was trained under, or `"mixed"`.
    # CheckpointManifest
    def TrainingBlockMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Per-study-stage block modes, in study-stage order (mixed-mode only).
    # CheckpointManifest
    def TrainingBlockModePerStage(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # CheckpointManifest
    def TrainingBlockModePerStageLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CheckpointManifest
    def TrainingBlockModePerStageIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        return o == 0

    # Objective cost-scale factor the writing study resolved; absent when unmarked.
    # CheckpointManifest
    def CostScaleFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CheckpointManifestStart(builder):
    builder.StartObject(19)

def Start(builder):
    CheckpointManifestStart(builder)

def CheckpointManifestAddFormatVersion(builder, formatVersion):
    builder.PrependUint32Slot(0, formatVersion, 0)

def AddFormatVersion(builder, formatVersion):
    CheckpointManifestAddFormatVersion(builder, formatVersion)

def CheckpointManifestAddCobreVersion(builder, cobreVersion):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cobreVersion), 0)

def AddCobreVersion(builder, cobreVersion):
    CheckpointManifestAddCobreVersion(builder, cobreVersion)

def CheckpointManifestAddCreatedAt(builder, createdAt):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(createdAt), 0)

def AddCreatedAt(builder, createdAt):
    CheckpointManifestAddCreatedAt(builder, createdAt)

def CheckpointManifestAddNumStages(builder, numStages):
    builder.PrependUint32Slot(3, numStages, 0)

def AddNumStages(builder, numStages):
    CheckpointManifestAddNumStages(builder, numStages)

def CheckpointManifestAddNPools(builder, nPools):
    builder.PrependUint32Slot(4, nPools, 0)

def AddNPools(builder, nPools):
    CheckpointManifestAddNPools(builder, nPools)

def CheckpointManifestAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    CheckpointManifestAddNodes(builder, nodes)

def CheckpointManifestStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems: int) -> int:
    return CheckpointManifestStartNodesVector(builder, numElems)

def CheckpointManifestAddEdges(builder, edges):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder, edges):
    CheckpointManifestAddEdges(builder, edges)

def CheckpointManifestStartEdgesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdgesVector(builder, numElems: int) -> int:
    return CheckpointManifestStartEdgesVector(builder, numElems)

def CheckpointManifestAddCompletedIterations(builder, completedIterations):
    builder.PrependUint32Slot(7, completedIterations, 0)

def AddCompletedIterations(builder, completedIterations):
    CheckpointManifestAddCompletedIterations(builder, completedIterations)

def CheckpointManifestAddFinalLowerBound(builder, finalLowerBound):
    builder.PrependFloat64Slot(8, finalLowerBound, 0.0)

def AddFinalLowerBound(builder, finalLowerBound):
    CheckpointManifestAddFinalLowerBound(builder, finalLowerBound)

def CheckpointManifestAddBestUpperBound(builder, bestUpperBound):
    builder.PrependFloat64Slot(9, bestUpperBound, 0.0)

def AddBestUpperBound(builder, bestUpperBound):
    CheckpointManifestAddBestUpperBound(builder, bestUpperBound)

def CheckpointManifestAddMaxIterations(builder, maxIterations):
    builder.PrependUint32Slot(10, maxIterations, 0)

def AddMaxIterations(builder, maxIterations):
    CheckpointManifestAddMaxIterations(builder, maxIterations)

def CheckpointManifestAddForwardPasses(builder, forwardPasses):
    builder.PrependUint32Slot(11, forwardPasses, 0)

def AddForwardPasses(builder, forwardPasses):
    CheckpointManifestAddForwardPasses(builder, forwardPasses)

def CheckpointManifestAddWarmStartCuts(builder, warmStartCuts):
    builder.PrependUint32Slot(12, warmStartCuts, 0)

def AddWarmStartCuts(builder, warmStartCuts):
    CheckpointManifestAddWarmStartCuts(builder, warmStartCuts)

def CheckpointManifestAddWarmStartCounts(builder, warmStartCounts):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(warmStartCounts), 0)

def AddWarmStartCounts(builder, warmStartCounts):
    CheckpointManifestAddWarmStartCounts(builder, warmStartCounts)

def CheckpointManifestStartWarmStartCountsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWarmStartCountsVector(builder, numElems: int) -> int:
    return CheckpointManifestStartWarmStartCountsVector(builder, numElems)

def CheckpointManifestAddRngSeed(builder, rngSeed):
    builder.PrependUint64Slot(14, rngSeed, 0)

def AddRngSeed(builder, rngSeed):
    CheckpointManifestAddRngSeed(builder, rngSeed)

def CheckpointManifestAddTotalVisitedStates(builder, totalVisitedStates):
    builder.PrependUint64Slot(15, totalVisitedStates, 0)

def AddTotalVisitedStates(builder, totalVisitedStates):
    CheckpointManifestAddTotalVisitedStates(builder, totalVisitedStates)

def CheckpointManifestAddTrainingBlockMode(builder, trainingBlockMode):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(trainingBlockMode), 0)

def AddTrainingBlockMode(builder, trainingBlockMode):
    CheckpointManifestAddTrainingBlockMode(builder, trainingBlockMode)

def CheckpointManifestAddTrainingBlockModePerStage(builder, trainingBlockModePerStage):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(trainingBlockModePerStage), 0)

def AddTrainingBlockModePerStage(builder, trainingBlockModePerStage):
    CheckpointManifestAddTrainingBlockModePerStage(builder, trainingBlockModePerStage)

def CheckpointManifestStartTrainingBlockModePerStageVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTrainingBlockModePerStageVector(builder, numElems: int) -> int:
    return CheckpointManifestStartTrainingBlockModePerStageVector(builder, numElems)

def CheckpointManifestAddCostScaleFactor(builder, costScaleFactor):
    builder.PrependFloat64Slot(18, costScaleFactor, 0.0)

def AddCostScaleFactor(builder, costScaleFactor):
    CheckpointManifestAddCostScaleFactor(builder, costScaleFactor)

def CheckpointManifestEnd(builder):
    return builder.EndObject()

def End(builder):
    return CheckpointManifestEnd(builder)
