# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

# State-vector dimension class for one entry of an entity manifest.
class EntityType(object):
    HydroStorage = 0
    HydroInflowLag = 1
    AnticipatedThermalState = 2
    HydroTransitBucket = 3
