# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Per-slot entity identity for one state-vector dimension. Element type of
# the `entity_manifest` vectors.
#
# `subindex` is the secondary index within the owning entity: the 1-based AR
# lag order for `HydroInflowLag`, the ring-buffer slot for
# `AnticipatedThermalState`, the maturity lag `d` for `HydroTransitBucket`
# (`entity_id` is the downstream hydro), and `0` for `HydroStorage`.
class EntitySlot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EntitySlot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntitySlot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EntitySlotBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # EntitySlot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Dimension class of this state slot.
    # EntitySlot
    def EntityType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Owning entity's id, matching the `entity_id` columns in `entities.csv`
    # and `bounds.parquet`.
    # EntitySlot
    def EntityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Secondary index within the owning entity (per-type meaning above).
    # EntitySlot
    def Subindex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Whether the owning entity was operationally active at this slot's stage.
    # EntitySlot
    def WasActive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Canonical absolute delivery/arrival calendar date for this slot, encoded
    # `year * 10000 + month * 100 + day` (`YYYYMMDD`, sortable); `day = 01` for
    # the month-granular anticipated-commitment anchors. Stable across stage
    # resolutions: the same calendar month maps to the same date whether resolved
    # from a weekly or a monthly stage. Sentinel `-2147483648` (`i32::MIN`) when
    # the slot has no delivery semantics, and the value a reader yields when the
    # field is absent from a pre-`id:5` buffer (forward-compatible default).
    # EntitySlot
    def DeliveryDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EntitySlotStart(builder):
    builder.StartObject(6)

def Start(builder):
    EntitySlotStart(builder)

def EntitySlotAddEntityType(builder, entityType):
    builder.PrependInt8Slot(0, entityType, 0)

def AddEntityType(builder, entityType):
    EntitySlotAddEntityType(builder, entityType)

def EntitySlotAddEntityId(builder, entityId):
    builder.PrependInt32Slot(1, entityId, 0)

def AddEntityId(builder, entityId):
    EntitySlotAddEntityId(builder, entityId)

def EntitySlotAddSubindex(builder, subindex):
    builder.PrependUint32Slot(2, subindex, 0)

def AddSubindex(builder, subindex):
    EntitySlotAddSubindex(builder, subindex)

def EntitySlotAddWasActive(builder, wasActive):
    builder.PrependBoolSlot(3, wasActive, 0)

def AddWasActive(builder, wasActive):
    EntitySlotAddWasActive(builder, wasActive)

def EntitySlotAddDeliveryDate(builder, deliveryDate):
    builder.PrependInt32Slot(5, deliveryDate, 0)

def AddDeliveryDate(builder, deliveryDate):
    EntitySlotAddDeliveryDate(builder, deliveryDate)

def EntitySlotEnd(builder):
    return builder.EndObject()

def End(builder):
    return EntitySlotEnd(builder)
