# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# One node of the checkpoint's policy-graph manifest. Element type of
# `CheckpointManifest.nodes`.
#
# `pool_id` is the node → pool map: a reader resolves node `id`'s affine pieces
# as `pool_id`'s `StageCuts` payload (leaf nodes sharing a pool name the same
# `pool_id`).
class ManifestNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ManifestNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsManifestNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ManifestNodeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # ManifestNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Declared node id.
    # ManifestNode
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Graph-stage id this node sits at.
    # ManifestNode
    def StageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Pool whose payload holds this node's affine pieces.
    # ManifestNode
    def PoolId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ManifestNodeStart(builder):
    builder.StartObject(3)

def Start(builder):
    ManifestNodeStart(builder)

def ManifestNodeAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    ManifestNodeAddId(builder, id)

def ManifestNodeAddStageId(builder, stageId):
    builder.PrependInt32Slot(1, stageId, 0)

def AddStageId(builder, stageId):
    ManifestNodeAddStageId(builder, stageId)

def ManifestNodeAddPoolId(builder, poolId):
    builder.PrependUint32Slot(2, poolId, 0)

def AddPoolId(builder, poolId):
    ManifestNodeAddPoolId(builder, poolId)

def ManifestNodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ManifestNodeEnd(builder)
