# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Root table for `policy/states/<stage>.bin`.
#
# Visited forward-pass trial points for one stage. Only emitted when
# `exports.states = true` in the run configuration.
class StageStates(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageStates()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageStates(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StageStatesBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # StageStates
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Study stage index (0-based).
    # StageStates
    def StageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Length of each state vector. Matches the length of the embedded
    # `entity_manifest`, which carries the per-slot identity of each
    # state-vector dimension.
    # StageStates
    def StateDimension(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Number of state vectors stored.
    # StageStates
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Flat row-major buffer; length equals `count * state_dimension`.
    # StageStates
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # StageStates
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # StageStates
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageStates
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Per-slot entity identity. Length equals `StageStates.state_dimension`.
    # StageStates
    def EntityManifest(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cobre.IO.Policy.EntitySlot import EntitySlot
            obj = EntitySlot()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StageStates
    def EntityManifestLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageStates
    def EntityManifestIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Policy-graph node identity (distinct from `stage_id` once a graph
    # carries more than one node per stage). Default `-1` (no node identity
    # resolved) — the value a reader yields when the field is absent from a
    # pre-`id:5` buffer (forward-compatible default).
    # StageStates
    def NodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def StageStatesStart(builder):
    builder.StartObject(6)

def Start(builder):
    StageStatesStart(builder)

def StageStatesAddStageId(builder, stageId):
    builder.PrependUint32Slot(0, stageId, 0)

def AddStageId(builder, stageId):
    StageStatesAddStageId(builder, stageId)

def StageStatesAddStateDimension(builder, stateDimension):
    builder.PrependUint32Slot(1, stateDimension, 0)

def AddStateDimension(builder, stateDimension):
    StageStatesAddStateDimension(builder, stateDimension)

def StageStatesAddCount(builder, count):
    builder.PrependUint32Slot(2, count, 0)

def AddCount(builder, count):
    StageStatesAddCount(builder, count)

def StageStatesAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    StageStatesAddData(builder, data)

def StageStatesStartDataVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartDataVector(builder, numElems: int) -> int:
    return StageStatesStartDataVector(builder, numElems)

def StageStatesAddEntityManifest(builder, entityManifest):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(entityManifest), 0)

def AddEntityManifest(builder, entityManifest):
    StageStatesAddEntityManifest(builder, entityManifest)

def StageStatesStartEntityManifestVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntityManifestVector(builder, numElems: int) -> int:
    return StageStatesStartEntityManifestVector(builder, numElems)

def StageStatesAddNodeId(builder, nodeId):
    builder.PrependInt32Slot(5, nodeId, -1)

def AddNodeId(builder, nodeId):
    StageStatesAddNodeId(builder, nodeId)

def StageStatesEnd(builder):
    return builder.EndObject()

def End(builder):
    return StageStatesEnd(builder)
