# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Root table for `policy/basis/<stage>.bin`.
#
# LP simplex basis checkpoint for one stage. `column_status`/`row_status` bytes
# are the canonical BasisStatus discriminant space (0..=6), a strict superset of
# the HiGHS code space this format previously carried, so files written before
# the canonical encoding decode identically.
class StageBasis(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageBasis()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageBasis(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StageBasisBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # StageBasis
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Stage index (0-based).
    # StageBasis
    def StageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Training iteration that produced this basis.
    # StageBasis
    def Iteration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Number of LP columns. Equals `column_status.length`.
    # StageBasis
    def NumColumns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Number of LP rows. Equals `row_status.length`.
    # StageBasis
    def NumRows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Canonical BasisStatus discriminant per LP column (variable).
    # StageBasis
    def ColumnStatus(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # StageBasis
    def ColumnStatusAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # StageBasis
    def ColumnStatusLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageBasis
    def ColumnStatusIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Canonical BasisStatus discriminant per LP row (constraint).
    # StageBasis
    def RowStatus(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # StageBasis
    def RowStatusAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # StageBasis
    def RowStatusLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageBasis
    def RowStatusIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Number of trailing entries in `row_status` that correspond to
    # affine-piece rows (as opposed to structural constraints).
    # StageBasis
    def NumCutRows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def StageBasisStart(builder):
    builder.StartObject(7)

def Start(builder):
    StageBasisStart(builder)

def StageBasisAddStageId(builder, stageId):
    builder.PrependUint32Slot(0, stageId, 0)

def AddStageId(builder, stageId):
    StageBasisAddStageId(builder, stageId)

def StageBasisAddIteration(builder, iteration):
    builder.PrependUint32Slot(1, iteration, 0)

def AddIteration(builder, iteration):
    StageBasisAddIteration(builder, iteration)

def StageBasisAddNumColumns(builder, numColumns):
    builder.PrependUint32Slot(2, numColumns, 0)

def AddNumColumns(builder, numColumns):
    StageBasisAddNumColumns(builder, numColumns)

def StageBasisAddNumRows(builder, numRows):
    builder.PrependUint32Slot(3, numRows, 0)

def AddNumRows(builder, numRows):
    StageBasisAddNumRows(builder, numRows)

def StageBasisAddColumnStatus(builder, columnStatus):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(columnStatus), 0)

def AddColumnStatus(builder, columnStatus):
    StageBasisAddColumnStatus(builder, columnStatus)

def StageBasisStartColumnStatusVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartColumnStatusVector(builder, numElems: int) -> int:
    return StageBasisStartColumnStatusVector(builder, numElems)

def StageBasisAddRowStatus(builder, rowStatus):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rowStatus), 0)

def AddRowStatus(builder, rowStatus):
    StageBasisAddRowStatus(builder, rowStatus)

def StageBasisStartRowStatusVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartRowStatusVector(builder, numElems: int) -> int:
    return StageBasisStartRowStatusVector(builder, numElems)

def StageBasisAddNumCutRows(builder, numCutRows):
    builder.PrependUint32Slot(6, numCutRows, 0)

def AddNumCutRows(builder, numCutRows):
    StageBasisAddNumCutRows(builder, numCutRows)

def StageBasisEnd(builder):
    return builder.EndObject()

def End(builder):
    return StageBasisEnd(builder)
