# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# One directed edge of the policy-graph manifest, with its transition
# probability. Element type of `CheckpointManifest.edges`.
class ManifestEdge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ManifestEdge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsManifestEdge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ManifestEdgeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # ManifestEdge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Source node id.
    # ManifestEdge
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Target node id.
    # ManifestEdge
    def TargetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Transition probability `P(source -> target)`.
    # ManifestEdge
    def Probability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ManifestEdgeStart(builder):
    builder.StartObject(3)

def Start(builder):
    ManifestEdgeStart(builder)

def ManifestEdgeAddSourceId(builder, sourceId):
    builder.PrependInt32Slot(0, sourceId, 0)

def AddSourceId(builder, sourceId):
    ManifestEdgeAddSourceId(builder, sourceId)

def ManifestEdgeAddTargetId(builder, targetId):
    builder.PrependInt32Slot(1, targetId, 0)

def AddTargetId(builder, targetId):
    ManifestEdgeAddTargetId(builder, targetId)

def ManifestEdgeAddProbability(builder, probability):
    builder.PrependFloat64Slot(2, probability, 0.0)

def AddProbability(builder, probability):
    ManifestEdgeAddProbability(builder, probability)

def ManifestEdgeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ManifestEdgeEnd(builder)
