# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Policy

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Root table for `policy/cuts/<pool>.bin`.
class StageCuts(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageCuts()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageCuts(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StageCutsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x56\x46", size_prefixed=size_prefixed)

    # StageCuts
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pool id (0-based) — the storage-unit key naming `cuts/<pool>.bin`.
    # StageCuts
    def StageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # State-vector dimension. Matches the coefficient-vector length on
    # every `AffinePiece` and the length of the embedded `entity_manifest`,
    # which carries the per-slot identity of each state-vector dimension.
    # StageCuts
    def StateDimension(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Total preallocated piece slots in the pool.
    # StageCuts
    def Capacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Number of slots `[0..warm_start_count)` loaded from a prior
    # artifact at run start.
    # StageCuts
    def WarmStartCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Pieces currently held for this pool. Length equals
    # `populated_count`.
    # StageCuts
    def Cuts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cobre.IO.Policy.AffinePiece import AffinePiece
            obj = AffinePiece()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StageCuts
    def CutsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageCuts
    def CutsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Indices into `cuts` of pieces currently active in the LP.
    # StageCuts
    def ActiveCutIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # StageCuts
    def ActiveCutIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # StageCuts
    def ActiveCutIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageCuts
    def ActiveCutIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Number of filled slots in the pool. Equals `cuts.length`.
    # StageCuts
    def PopulatedCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Per-slot entity identity. Length equals `StageCuts.state_dimension`.
    # StageCuts
    def EntityManifest(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cobre.IO.Policy.EntitySlot import EntitySlot
            obj = EntitySlot()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StageCuts
    def EntityManifestLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageCuts
    def EntityManifestIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Objective cost-scale factor the writing study resolved — the provenance
    # marker making each cut's `coefficients`/`intercept` scale-independent at
    # rest. A reader yields no value (absent) for a pre-`id:8` buffer.
    # StageCuts
    def CostScaleFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Owning node's policy-graph id when this pool has a single owner, else `-1`
    # (a shared pool, which is never a boundary source). Default `-1` is also the
    # value a reader yields when the field is absent from a pre-`id:8` buffer.
    # StageCuts
    def NodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # Graph-stage id of the node(s) owning this pool (`pool_stage` resolved
    # through the study stage ids) — the boundary-resolution key. Default `-1` is
    # also the value a reader yields when the field is absent from a pre-`id:8`
    # buffer.
    # StageCuts
    def GraphStageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def StageCutsStart(builder):
    builder.StartObject(11)

def Start(builder):
    StageCutsStart(builder)

def StageCutsAddStageId(builder, stageId):
    builder.PrependUint32Slot(0, stageId, 0)

def AddStageId(builder, stageId):
    StageCutsAddStageId(builder, stageId)

def StageCutsAddStateDimension(builder, stateDimension):
    builder.PrependUint32Slot(1, stateDimension, 0)

def AddStateDimension(builder, stateDimension):
    StageCutsAddStateDimension(builder, stateDimension)

def StageCutsAddCapacity(builder, capacity):
    builder.PrependUint32Slot(2, capacity, 0)

def AddCapacity(builder, capacity):
    StageCutsAddCapacity(builder, capacity)

def StageCutsAddWarmStartCount(builder, warmStartCount):
    builder.PrependUint32Slot(3, warmStartCount, 0)

def AddWarmStartCount(builder, warmStartCount):
    StageCutsAddWarmStartCount(builder, warmStartCount)

def StageCutsAddCuts(builder, cuts):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(cuts), 0)

def AddCuts(builder, cuts):
    StageCutsAddCuts(builder, cuts)

def StageCutsStartCutsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCutsVector(builder, numElems: int) -> int:
    return StageCutsStartCutsVector(builder, numElems)

def StageCutsAddActiveCutIndices(builder, activeCutIndices):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(activeCutIndices), 0)

def AddActiveCutIndices(builder, activeCutIndices):
    StageCutsAddActiveCutIndices(builder, activeCutIndices)

def StageCutsStartActiveCutIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActiveCutIndicesVector(builder, numElems: int) -> int:
    return StageCutsStartActiveCutIndicesVector(builder, numElems)

def StageCutsAddPopulatedCount(builder, populatedCount):
    builder.PrependUint32Slot(6, populatedCount, 0)

def AddPopulatedCount(builder, populatedCount):
    StageCutsAddPopulatedCount(builder, populatedCount)

def StageCutsAddEntityManifest(builder, entityManifest):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(entityManifest), 0)

def AddEntityManifest(builder, entityManifest):
    StageCutsAddEntityManifest(builder, entityManifest)

def StageCutsStartEntityManifestVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntityManifestVector(builder, numElems: int) -> int:
    return StageCutsStartEntityManifestVector(builder, numElems)

def StageCutsAddCostScaleFactor(builder, costScaleFactor):
    builder.PrependFloat64Slot(8, costScaleFactor, 0.0)

def AddCostScaleFactor(builder, costScaleFactor):
    StageCutsAddCostScaleFactor(builder, costScaleFactor)

def StageCutsAddNodeId(builder, nodeId):
    builder.PrependInt32Slot(9, nodeId, -1)

def AddNodeId(builder, nodeId):
    StageCutsAddNodeId(builder, nodeId)

def StageCutsAddGraphStageId(builder, graphStageId):
    builder.PrependInt32Slot(10, graphStageId, -1)

def AddGraphStageId(builder, graphStageId):
    StageCutsAddGraphStageId(builder, graphStageId)

def StageCutsEnd(builder):
    return builder.EndObject()

def End(builder):
    return StageCutsEnd(builder)
